IOTMBL-651: Fix ERROR: mbl-console-image-1.0-r0 do_image_wic. (#175)
The following provides further information on this commit:
- The mbl-master build is broken for MACHINE=imx7s-warp-mbl, bitbake target
  mbl-console-image-test with the following error:
    ERROR: mbl-console-image-1.0-r0 do_image_wic: Function failed: do_image_wic
    (... lines removed  ... )
    | DEBUG: Python function set_image_size finished
    | DEBUG: Executing python function extend_recipe_sysroot
    | ERROR: _exec_cmd: install -m 0644 -D .. boot.scr returned '1' instead of 0
- The error is caused by the boot.scr file not being present in the DEPLOY_DIR.
  This is because the mbl-boot-src.bb recipe has not been run, because there
  mbl-console-image-test doesn't depend on mbl-boot-scr.bb (when it should).
- This commit fixes the problem by adding a mbl-boot-scr dependency in
  u-boot-fslc_%.bbappend. Warp7 depends on u-boot-fslc_*.bb rather than u-boot_*
  (as in the case of RaspberryPi3).

Signed-off-by: Simon Hughes <simon.hughes@arm.com>