rpi3: optee_os: Build OP-TEE for RPi3 (#198)
rpi3: optee_os: Build OP-TEE for RPi3

The following provides further information on this commit:
- Build OP-TEE for RPi3.
- Update ATF recipe to use OP-TEE as BL32 in FIP.
- IOTMBL-755: Fix optee-os_%.bb for multi-board builds in same workspace.
  - If a raspberrypi3-mbl image is built, and then in the same workspace a
    imx7s-warp7-mbl image is build, then the optee_os recipe fails with the
    error:
      | DEBUG: Executing shell function do_compile
      | NOTE: make -j 48 PLATFORM=imx-mx7swarp7 CROSS_COMPILE_core=...
       <lines deleted to save space>
      | core/arch/arm/plat-imx/conf.mk:80: *** CFG_TEE_CORE_NB_CORE is set
        to '2' (from file) but its value must be '1'.  Stop.
      | ERROR: oe_runmake failed
      | WARNING: exit code 1 from a shell command.
      | ERROR: Function failed: do_compile ...
  - This is fixed by changing the EXTRA_OEMAKE_imx7s-warp-mbl to include
    CFG_TEE_CORE_NB_CORE=1.
- IOTMBL-755: Change SRCREV & SRC_URI to point at Linaro staging repo.
  - Changing the SRCREV & SRC_URI to point to upstream breaks the optee-test
    recipe with the following error:
      testframework.c:167:2: error: implicit declaration of function
      'mpa_init_scratch_mem'; did you mean 'mpa_init_static'?
      [-Werror=implicit-function-declaration]
  - Hence, this commit now uses the last known good revision in the Linaro
    staging repo, where the optee-test recipe builds OK.