IOTMBL-1959: Merge meta-freescale-(3rdparty-)mbl linux-fslc*.bbappend into 1 file.
The following provides more information on this commit:
- There are a number of issues related to the currently linux-fslc processing,
  which is used for the imx7s-warp-mbl and imx7d-warp-mbl targets.
- In the current MBL workspace, the following linux-fslc_*.bb related files
  exist:
    - meta-freescale/recipes-kernel/linux/linux-fslc_5.0.bb
    - meta-mbl/meta-freescale-3rdparty-mbl/recipes-kernel/linux/
							linux-fslc_%.bbappend
    - meta-mbl/meta-freescale-mbl/recipes-kernel/linux/linux-fslc_%.bbappend
    - meta-freescale-3rdparty/recipes-kernel/linux/linux-fslc_%.bbappend
- imx7* machine.conf files are currently stored in meta-freescale-3rdparty-mbl
  whereas the main MBL linux-fslc*.bbappend processing is stored in
  (confusingly) meta-mbl/meta-freescale-mbl/recipes-kernel/linux/
  linux-fslc_%.bbappend.
- Also, meta-freescale-mbl/recipes-kernel/linux/linux-fslc_%.bbappend SRC_URI
  uses "+=" which is incorrect (it should use "=") because multiple SCMs are
  configured in SRC_URI (e.g. from meta-freescale/recipes-kernel/linux/
  linux-fslc_5.0.bb) which results in the following intermittent error:
    ERROR: ExpansionError during parsing <.....>/linux-fslc_5.0.bb
    <.....>
    raise FetchError("The SRCREV_FORMAT variable must be set when multiple SCMs
- To resolve these issues, this commit merges meta-freescale-mbl/recipes-kernel/
  linux/linux-fslc*.bbappend and meta-freescale-3rdparty-mbl/recipes-kernel/
  linux/linux-fslc*.bbappend into one file
  meta-freescale-3rdparty-mbl/recipes-kernel/linux/linux-fslc*.bbappend.
- This results in 2 copies of
  0001-menuconfig-check-lxdiaglog.sh-Allow-specification-of.patch being checked
  into the repo, a new copy for use by the new linux-fslc*.bbappend, and
  the original being used by linux-imx*.bbappend. However, this is considered
  preferable to having the linux-fslc*.bbappend hard-code a path from
  meta-freescale-mbl to meta-freescale-3rdparty-mbl, or vice versa.