IOTMBL-651: Fix ERROR: mbl-boot-scr-1.0-r0 do_deploy.
The following provides more information on this commit:
- mbl-console-image-test doesn't build with the following error message:
    ERROR: mbl-boot-scr-1.0-r0 do_deploy: The recipe mbl-boot-scr is
    trying to install files into a shared area when those files
    already exist.
- The error is caused by both the following recipes copying boot.scr to
  the DEPLOY_DIR:
      - rpi-u-boot-scr.bb
      - mbl-boot-scr.bb
  rpi-u-boot-scr.bb should not be run as the mbl-boot-scr.bb
  creates the required boot.scr.
- This commit removes the mbl-boot-scr package from the IMAGE_INSTALL
  list in mbl-console-image.bb as the package isn't installed.
- u-boot_%.bbappend is modified to correctly remove rpi-u-boot-scr from
  the dependencies of the u-boot recipe.
- raspberrypi3-mbl.conf is modified to blacklist the rpi-u-boot-scr
  packagename such that if it's included then an error will be generated.

Signed-off-by: Simon Hughes <simon.hughes@arm.com>