Revert "rpi3: separate fip into two parts. (#348)" (#383)
This reverts commit 605814ee4887241aed9876586308316f42d3d4db.

For IOTMBL-1625: RPi3 boot failure due to SD-Card read failures.

When I try to boot my RPi3 I get the following output and then a hang.
Reverting 605814ee4887241aed9876586308316f42d3d4db fixes this.

NOTICE:  BL1: v2.0(release):atf-pr1768-128-g4021f04
NOTICE:  BL1: Built : 12:13:30, Feb 12 2019
INFO:    BL1: RAM 0x100ee000 - 0x100fa000
INFO:    Using crypto library 'mbed TLS'
NOTICE:  rpi3: Detected: Raspberry Pi 3 Model B (1GB, Embest, China)
[0x00a22082]
INFO:    BL1: Loading BL2
INFO:    Loading image id=6 at address 0x100b4000
INFO:    Image id=6 loaded: 0x100b4000 - 0x100b446f
INFO:    Loading image id=1 at address 0x100b4000
INFO:    Image id=1 loaded: 0x100b4000 - 0x100c95e0
NOTICE:  BL1: Booting BL2
INFO:    Entry point address = 0x100b4000
INFO:    SPSR = 0x3c5
NOTICE:  BL2: v2.0(release):atf-pr1768-128-g4021f04
NOTICE:  BL2: Built : 12:13:21, Feb 12 2019
INFO:    Using crypto library 'mbed TLS'
INFO:    BL2: Doing platform setup
INFO:    BL2: Loading image id 3
ERROR:   rpi3_sdhost: transfer FIFO word 122: 0x21
INFO:    rpi3_sdhost: HC_COMMAND:        0x00004052
INFO:    rpi3_sdhost: HC_ARGUMENT:       0x00000800
INFO:    rpi3_sdhost: HC_TIMEOUTCOUNTER: 0x00f00000
INFO:    rpi3_sdhost: HC_CLOCKDIVISOR:   0x0000027b
INFO:    rpi3_sdhost: HC_RESPONSE_0:     0x00000900
INFO:    rpi3_sdhost: HC_RESPONSE_1:     0x00001269
INFO:    rpi3_sdhost: HC_RESPONSE_2:     0xffffffff
INFO:    rpi3_sdhost: HC_RESPONSE_3:     0x0002400f
INFO:    rpi3_sdhost: HC_HOSTSTATUS:     0x00000021
INFO:    rpi3_sdhost: HC_POWER:          0x00000001
INFO:    rpi3_sdhost: HC_DEBUG:          0x00010902
INFO:    rpi3_sdhost: HC_HOSTCONFIG:     0x0000040e
INFO:    rpi3_sdhost: HC_BLOCKSIZE:      0x000001d4
INFO:    rpi3_sdhost: HC_BLOCKCOUNT:     0x00000001
ERROR:   rpi3_sdhost: transfer FIFO word 122: 0x421
[snip]
NFO:    rpi3_sdhost: HC_COMMAND:        0x00004052
INFO:    rpi3_sdhost: HC_ARGUMENT:       0x00000800
INFO:    rpi3_sdhost: HC_TIMEOUTCOUNTER: 0x00f00000
INFO:    rpi3_sdhost: HC_CLOCKDIVISOR:   0x0000027b
INFO:    rpi3_sdhost: HC_RESPONSE_0:     0x00000900
INFO:    rpi3_sdhost: HC_RESPONSE_1:     0x00001269
INFO:    rpi3_sdhost: HC_RESPONSE_2:     0xffffffff
INFO:    rpi3_sdhost: HC_RESPONSE_3:     0x0002c01f
INFO:    rpi3_sdhost: HC_HOSTSTATUS:     0x00000421
INFO:    rpi3_sdhost: HC_POWER:          0x00000001
INFO:    rpi3_sdhost: HC_DEBUG:          0x00010902
INFO:    rpi3_sdhost: HC_HOSTCONFIG:     0x0000040e
INFO:    rpi3_sdhost: HC_BLOCKSIZE:      0x000001d4
INFO:    rpi3_sdhost: HC_BLOCKCOUNT:     0x00000001
ERROR:   rpi3_sdhost: transfer FIFO word