IOTMBL-645: Fix libaio recipe to support libaio-native target. (#173)
The following provides more information on this commit:
- The build for raspberrypi3-mbl reports the following error:
  ERROR: Nothing PROVIDES 'libaio-native' (but virtual:native:
  <path_removed>/layers/meta-openembedded/meta-oe/recipes-support/lvm2/
  libdevmapper_2.02.180.bb DEPENDS on or otherwise requires it).
- This error is due to the libdevmapper recipe depending on
  libaio-native package, but there is no provider of that package.
- This commit fixes the problem by using the BBCLASSEXTEND = "native"
  directive in the libaio recipe to extend its use to being a
  provider for libaio-native.

Signed-off-by: Simon Hughes <simon.hughes@arm.com>