IOTMBL-438: Fix optee_test errors due to upgrade to GCC 8.1.1
The following provides more information on this commit:
- The following error has been fixed by patch
  0001-IOTMBL-438-Fix-optee_test-adbg_run.c-strncpy-Werror-.patch:
  "adbg_run.c:103:3: error: 'strncpy' specified bound depends on
  the length of the source argument [-Werror=stringop-overflow=]"
- The following error has been fixed by patch
  0001-IOTMBL-438-Fix-optee_test-error-memmove-Werror-array.patch:
  "error: 'memmove' pointer overflow between offset [0, 8] and
  size [4294967295, 2147483647] accessing array 'tmp' with type
  'uint8_t[1024]' {aka 'unsigned char[1024]'} [-Werror=array-bounds]"

Signed-off-by: Simon Hughes <simon.hughes@arm.com>