meta-linaro-mbl: optee-os: Fix compilation error when TRACE_LEVEL=0
Compiling optee-os for arm64 with the flag CFG_TEE_CORE_LOG_LEVEL=0
(which sets TRACE_LEVEL=0) fails with the following message:
core/arch/arm/kernel/abort.c: In function '__print_stack_unwind':
core/arch/arm/kernel/abort.c:85:2: error: too few arguments to function 'print_stack_arm64'
  print_stack_arm64(TRACE_ERROR, &state, thread_stack_start(),

The "bool kernel_stack __unused" parameter needs to be removed from
print_stack_arm64 function to get optee-os compiled.